### ISSUE TITLE
Mic / Drm switch style

### ISSUE THREAD

**Issue by davidfrosch** [Ichaelus/bitflipper#2]
change to analog style flip-switch
![image](https://user-images.githubusercontent.com/36916479/97561899-1ffde100-19e1-11eb-8a33-9058f4883b77.png)

**Comment by davidfrosch** [comment]
![image](https://user-images.githubusercontent.com/36916479/97628895-9de7d980-1a2d-11eb-890b-792c9deca1b7.png)

**Comment by Ichaelus** [comment]
IMHO this feature request collides with https://github.com/Ichaelus/bitflipper/issues/5, especially if we want to allow more than one input method.

**Comment by davidfrosch** [comment]
no, switching to the mix input will open the setup menu. see #5

**Comment by Ichaelus** [comment]
I fear this would be very confusing for the user, who is not used to a switch with constantly changing states. Usually a switch has two fixed states that will always be the same, no matter how often he uses it.
In our case, the two label scorresponding to the switches' state would change on every user interaction. An example:

````
// Initial state:
// The switch is set to "DRM", the drum machine plays
[DRM|SRC] 
[ x |   ]

// Clicking the switch will open the "setup menu" where the user chooses an input method
[DRM|SRC] 
[   | x ]

// Once the user has selected an input method the label of the current state must be adjusted
[SRC|MIC] 
[   | x ]

// We have to change the first label as the user should be able to change the input method again.
// Everybody will be confused by now.
````

**Comment by davidfrosch** [comment]
nothing would be constantly changing?

**Comment by davidfrosch** [comment]
its always the same input method: microphone.

same as eg. in zoom

**Comment by Ichaelus** [comment]
Then why would I want a switch if it is not visually changing anything? 😉

**Comment by davidfrosch** [comment]
![image](https://user-images.githubusercontent.com/36916479/97637165-73504d80-1a3a-11eb-81c5-eff6908aa794.png)

**Comment by davidfrosch** [comment]
![image](https://user-images.githubusercontent.com/36916479/97637199-7ea37900-1a3a-11eb-9f24-383becf4b68c.png)

**Comment by davidfrosch** [comment]
![image](https://user-images.githubusercontent.com/36916479/97637774-8d3e6000-1a3b-11eb-8fd2-9aaf3b209685.png)

**Comment by Ichaelus** [comment]
Button example styles:
```
border: 1px solid #464646;
border-radius: 1px;
background: linear-gradient(90deg, #1b1a1a 0%, #595959 10%, #1b1a1a 20%, #595959 30%, #1b1a1a 40%, #595959 50%, #1b1a1a 60%, #595959 70%, #1b1a1a 80%, #595959 90%, #1b1a1a 100%);
```

![Screenshot_2020-10-29 Bitflipper - 8 BIT reducer mangler](https://user-images.githubusercontent.com/1349321/97638101-2a00fd80-1a3c-11eb-9914-47696e5353c2.png)

**Comment by Ichaelus** [comment]
![grafik](https://user-images.githubusercontent.com/1349321/97799914-0bb02300-1c31-11eb-8b51-b726d6c10470.png)

**Comment by Ichaelus** [comment]
![grafik](https://user-images.githubusercontent.com/1349321/98596529-dada8880-22d7-11eb-8658-f2af404cdeb6.png)

@davidfrosch thats my first (actually fully functional) draft - what do you think? Feedback welcome.

**Comment by Ichaelus** [comment]
Pushing to the `staging` branch now triggers a separate deployment to a staging subdomain.
You can check out the current state of this issue by visiting https://bitflipper-staging.leimstaedtner.it/

**Comment by davidfrosch** [comment]
switch should change by pressing on the entire area, not only if the knob is in under the cursor
