### ISSUE TITLE
Move knob labels left of buttons

### ISSUE THREAD

**Issue by davidfrosch** [Ichaelus/bitflipper#3]
![image](https://user-images.githubusercontent.com/36916479/97562176-8256e180-19e1-11eb-8f6a-40a7345c4ec3.png)

buttons can be a bit smaller then + higher contrast for on/off state

**Comment by davidfrosch** [comment]
button colors:

mute : red
invert : blue
reset : white

**Comment by davidfrosch** [comment]
Labels:

RESET
INVERT
MUTE
BIT#

**Comment by davidfrosch** [comment]
![Uploading image.png…]()

**Comment by Ichaelus** [comment]
Blue styles
```
.bit-control--button.-reset:hover {
    background: radial-gradient(closest-side, #93e6ff, #48c2f2 70%);
}
.bit-control--button.-reset {
    background: radial-gradient(closest-side, #067394, #0063ba 70%);
    box-shadow: inset 0 0 3px #4b5086;
}
```

**Comment by Ichaelus** [comment]
![Bildschirmfoto am 2020-10-29 um 23 21 49](https://user-images.githubusercontent.com/1349321/97638784-916b7d00-1a3d-11eb-91c8-2e1c9508e459.png)

**Comment by Ichaelus** [comment]
Final version which made it to master:
![grafik](https://user-images.githubusercontent.com/1349321/97799935-313d2c80-1c31-11eb-9714-f3ea84f5eae8.png)
