### ISSUE TITLE
microphone input selection

### ISSUE THREAD

**Issue by davidfrosch** [Ichaelus/bitflipper#5]
allow user to select microphone input (and output?) for usage with sound equipment

**Comment by davidfrosch** [comment]
fancy version: output and input show the name of the input channel as labelling after selection

**Comment by Ichaelus** [comment]
Must-have feature.

If we're about to add an undefined number of inputs (as the user could have 0-999), we will sooner or later run into UI issues. On mobile, there is no space for more than two or three inputs. On desktop devices, there is enough space for now - but we should think about a responsive visual concept for the selection.

For example, we could limit the GUI to two "input slots". One is the currently connected audio source, the other will prompt the user to select the new source. When selected, the second slot will be used and the first is the new "select source" slot.
![grafik](https://user-images.githubusercontent.com/1349321/97628780-755fdf80-1a2d-11eb-8005-b30f1881e1ed.png)

**Comment by davidfrosch** [comment]
input selection should happen over a browser function not necessarily over the interface (only triggered through that)

**Comment by davidfrosch** [comment]
https://developers.google.com/web/updates/2015/10/media-devices

**Comment by Ichaelus** [comment]
Yes, but it should integrate neatly with the existing UI 🙂

**Comment by davidfrosch** [comment]
agreed, but given the limited time to work on stuff for now:
step 1: have it work 
step 2: make it look nice

;)

**Comment by Ichaelus** [comment]
Your time might be limited right now but I got plenty, haha.
Let's try to define the best case goal here, we can always take shortcuts later on 🙂

**Comment by Ichaelus** [comment]
solved via https://github.com/Ichaelus/bitflipper/commit/298ee16dd6dc84c5d6cc5065f3186472eebd63c6
